times = ('Atletico', 'Bahia', 'Botafogo', 'Ceara', 'Corinthians', 'Cruzeiro', 'Flamengo', 'Fluminence', 'Fortaleza', 'Gremio', 'Internacional', 'Juventude', 'Mirassol', 'Palmeiras', 'Red bul', 'Santos', 'Sao Paulo', 'Sport', 'Vasco da Gama', 'Vitoria')
print('-='*20)
print(f'Lista de times do brasileirão 2025 {times}')
print('-='*20)
print(f'Os 5 primeiros times são {times[0:5]}')
print('-='*20)
print(f'Os 4 ultimos são {times[-4:]}')
print('-='*20)
print(f'Times em ordem alfabetica são {sorted(times)}')
print('-='*20)
print(f'O Fluminence esta na {times.index("Fluminence")+1}° posição')